
// IMU Sensor Calibration Parameters
// Generated by imu_calibration.py on 2025-04-11 18:41:37

// Accelerometer calibration
float accel_bias[3] = {-1.503211f, 0.653368f, 7.384526f};  // X, Y, Z offsets
float accel_scale = 1.796287f;  // Scale factor

// Gyroscope calibration
float gyro_bias[3] = {-0.006421f, 0.088105f, 0.051579f};  // X, Y, Z offsets

// Magnetometer calibration
int16_t mag_bias[3] = {-138, 1368, -1678};  // X, Y, Z hard-iron offsets
float mag_scale[3] = {0.727626f, 1.502008f, 1.041783f};  // X, Y, Z soft-iron scale factors

// Function to apply calibration to accelerometer readings
void calibrateAccelerometer(float rawX, float rawY, float rawZ, float *calibX, float *calibY, float *calibZ) {
  *calibX = (rawX - accel_bias[0]) * accel_scale;
  *calibY = (rawY - accel_bias[1]) * accel_scale;
  *calibZ = (rawZ - accel_bias[2]) * accel_scale;
}

// Function to apply calibration to gyroscope readings
void calibrateGyroscope(float rawX, float rawY, float rawZ, float *calibX, float *calibY, float *calibZ) {
  *calibX = rawX - gyro_bias[0];
  *calibY = rawY - gyro_bias[1];
  *calibZ = rawZ - gyro_bias[2];
}

// Function to apply calibration to magnetometer readings
void calibrateMagnetometer(int16_t rawX, int16_t rawY, int16_t rawZ, float *calibX, float *calibY, float *calibZ) {
  *calibX = (rawX - mag_bias[0]) * mag_scale[0];
  *calibY = (rawY - mag_bias[1]) * mag_scale[1];
  *calibZ = (rawZ - mag_bias[2]) * mag_scale[2];
}
